name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: dcs-frontend-project
    runs-on: ubuntu-latest
    steps:
      - name: environment variables
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_WEATHER_ICON_BASE_URL: ${{ secrets.REACT_APP_FLAGS_BASE_URL }}
          REACT_APP_FLAGS_BASE_URL: ${{ secrets.REACT_APP_WEATHER_ICON_BASE_URL }}
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build

            